### ISSUE TITLE
problem with navbar

### ISSUE THREAD

**Issue by YooAshu** [Corrupteddisk/SpotifycloneWeb#104]
navbar is not is not good
there are many issue with the navbar after hamburger change
1->in desktop view there are same links twice one is above navbar 
2->in mobile there is two hamburger icons
![Screenshot 2024-01-14 121708](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/95643200/ba57c49a-2d72-466b-a8f1-b6f812908e75)
![Screenshot (99)](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/95643200/428af02e-d917-497d-8101-8747f64bc756)
![Screenshot (100)](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/95643200/aef8b5ba-544c-4035-9f80-3c3ca1d5b326)

**Comment by Sayan044** [comment]
Assigned to @YooAshu
