### ISSUE TITLE
Carousel is not visible in the website

### ISSUE THREAD

**Issue by rko0211** [Corrupteddisk/SpotifycloneWeb#118]
![Screen Shot 2024-01-15 at 01 02 59](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/97402824/53f2b621-907c-47f9-bdd1-842286ff5621)

**Comment by Sayan044** [comment]
Assigned to @rko0211

**Comment by soumit-s** [comment]
Carousel is visible
