### ISSUE TITLE
Sign in and sign up page is not Responsive

### ISSUE THREAD

**Issue by rko0211** [Corrupteddisk/SpotifycloneWeb#119]
![Screen Shot 2024-01-15 at 01 05 56](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/97402824/df06c97c-2f79-4c18-8b8a-530eb25b51b1)

![Screen Shot 2024-01-15 at 01 05 42](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/97402824/5282001c-8c91-40d5-acd0-e11d3d6b5181)

**Comment by Sayan044** [comment]
Assigned to @rko0211
