### ISSUE TITLE
Wrong songs play in party songs genre

### ISSUE THREAD

**Issue by lord-cyclone100** [Corrupteddisk/SpotifycloneWeb#125]
Wrong songs are played when the party songs genre is clicked I want to fix this issue

**Comment by Sayan044** [comment]
Assigned to @lord-cyclone100

**Comment by YooAshu** [comment]
Bhai , I don't understand, what do you mean by wrong song

**Comment by YooAshu** [comment]
Oo got it , ye maine dhyan nhi Diya
