### ISSUE TITLE
Arijit page responsiveness problem 

### ISSUE THREAD

**Issue by YooAshu** [Corrupteddisk/SpotifycloneWeb#131]
![Screenshot_20240115_114952](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/95643200/85cb44d1-d6e4-4767-8ed5-2c433fb0467e)

**Comment by Sayan044** [comment]
Assigned to @YooAshu

**Comment by rko0211** [comment]
Now it  was solved already, kindly check little bit

**Comment by Sayan044** [comment]
sure
