### ISSUE TITLE
[FEAT]: MAKE A PREMIUM OPTION TO SWOWCASE THE PREMIUM PLANS

### ISSUE THREAD

**Issue by AnitSarkar123** [Corrupteddisk/SpotifycloneWeb#16]
Assign me under Apertre'24

**Comment by Sayan044** [comment]
Assigned to @AnitSarkar123 
You have got 2 days to complete.

**Comment by AnitSarkar123** [comment]
firstly merge my pr then i going to work on that issue.. or merge confits will be arrived

**Comment by rko0211** [comment]
hey kindly assign me this task under apertre24.

**Comment by soumit-s** [comment]
Assigning to @rko0211
