### ISSUE TITLE
Contact us form need to be validate before submission

### ISSUE THREAD

**Issue by rko0211** [Corrupteddisk/SpotifycloneWeb#169]
Like sign in and sign up page, contact form is also required validation before submission

**Comment by Sayan044** [comment]
Assigned to @rko0211

**Comment by rko0211** [comment]
![Screen Shot 2024-01-17 at 18 09 50](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/97402824/6e6fbcc6-a8f2-46eb-8a6e-186699be2644)

Page is not Responsive completely, and give a heading of About US
