### ISSUE TITLE
light mode doesnot look good

### ISSUE THREAD

**Issue by YooAshu** [Corrupteddisk/SpotifycloneWeb#202]
light mode is not on all pages plus it just white bakground
assign me so i can fix this

**Comment by YooAshu** [comment]
and also it destroyed mobile view reponsiveness

**Comment by YooAshu** [comment]
![Screenshot (132)](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/95643200/84a3da61-6208-4974-9d63-fa9f16be75fa)

**Comment by Sayan044** [comment]
Assigned to @YooAshu
