### ISSUE TITLE
mobile view is not responsive 

### ISSUE THREAD

**Issue by YooAshu** [Corrupteddisk/SpotifycloneWeb#203]
mobile view is not responsive  , the dark mode button added does not uses proper css thats why mobile responsiveness i disturbed
![Screenshot (132)](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/95643200/5731c80e-09c4-4147-9202-990bfee73909)

**Comment by Sayan044** [comment]
Assigned to @YooAshu
