### ISSUE TITLE
adding a better sound icon and also improving the player controls.

### ISSUE THREAD

**Issue by Arkadipttv** [Corrupteddisk/SpotifycloneWeb#21]
![image](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/138896045/b5f6ac45-fdd4-4af1-992f-3ea94947dba2)

Please allow me to contribute on this segment

**Comment by Sayan044** [comment]
Please elaborate on what you want to add.

**Comment by deepbeatz** [comment]
its the same issue as #20 @Sayan044 assign me this issue. I will use better icons and they will have some appropriate hover effect

**Comment by deepbeatz** [comment]
plz assign me this issue because the player controls still look bad. i have already edited the css. just assign me and i will immediately send pr. @Sayan044

**Comment by Sayan044** [comment]
Assigned to @deepbeatz.
You have 2 days to complete.
