### ISSUE TITLE
[FEAT]Modify music playing section 

### ISSUE THREAD

**Issue by madhurima316** [Corrupteddisk/SpotifycloneWeb#26]
I want to modify the bottom part, which has the play button , so that it contains the song image also and the song name in proper orientation .

**Comment by Sayan044** [comment]
This issue is related to UI, but I've already assigned a UI issue. So try to find another issues

**Comment by Sayan044** [comment]
@madhurima316 assigned.

**Comment by madhurima316** [comment]
okay , thank you
