### ISSUE TITLE
changed the background 

### ISSUE THREAD

**Issue by Rai-Adhikary004** [Corrupteddisk/SpotifycloneWeb#28]
Changed the play music logo and added some Arijit Singh photos by changing the background .

**Comment by Sayan044** [comment]
You mean the UI part right?

**Comment by Sayan044** [comment]
@Rai-Adhikary004 assigned. You have one day for this issue.

**Comment by Mubashir2611** [comment]
Please assign me in this issue. I want to contribute this issue.
