### ISSUE TITLE
Creating a Home page which redirects to the login /signup page 

### ISSUE THREAD

**Issue by 123shreyanvi** [Corrupteddisk/SpotifycloneWeb#31]
linking the login/signup  page to the home page
the home page will be having some frequently asked questions section as other music web pages have on the home screen 
I'll add some animation on scroll too .

**Comment by Sayan044** [comment]
@123shreyanvi assigned.

**Comment by 123shreyanvi** [comment]
> @123shreyanvi assigned.

okay
