### ISSUE TITLE
add about page and make about link active

### ISSUE THREAD

**Issue by deepbeatz** [Corrupteddisk/SpotifycloneWeb#38]
@Sayan044 plz assign me this issue under proper tags

**Comment by Sayan044** [comment]
Assigned to @deepbeatz 
You have got 2 days to complete.

**Comment by deepbeatz** [comment]
For same type of issue #37 you have given the medium level tag, i think this also should have the medium level tag

**Comment by Sayan044** [comment]
done @deepbeatz

**Comment by rko0211** [comment]
Hey I want to work in this issue kindly assign me this

**Comment by Sneha123-zudo** [comment]
Please assign me this issue , I'm intrested in solving this issue

**Comment by Sayan044** [comment]
Assigned to @Sneha123-zudo 
You have 2 days to complete.
