### ISSUE TITLE
add a dark theme/light theme button

### ISSUE THREAD

**Issue by deepbeatz** [Corrupteddisk/SpotifycloneWeb#39]
@Sayan044 assign me this issue under proper tags

**Comment by Koustavjr** [comment]
@deepbeatz assigned.

**Comment by rko0211** [comment]
Hello I want to work in this issue kindly assign me

**Comment by lord-cyclone100** [comment]
@Koustavjr @Sayan044 
Pls assign this task to me

**Comment by Sneha123-zudo** [comment]
Please assign me this issue.

**Comment by soumit-s** [comment]
Assigning to @lord-cyclone100
