### ISSUE TITLE
Make the About Page responsive , attractive and change its CSS

### ISSUE THREAD

**Issue by Sapta-Dev27** [Corrupteddisk/SpotifycloneWeb#42]
The about page is made , but its not atractive , the fonts , the padding , margin .
I want to change the UI  of the about page , add hover effects , transitions and make it look more attractive

**Comment by Sayan044** [comment]
I have assigned you to make it responsive.
So only make the CSS attractive.

Assigned to @Sapta-Dev27

**Comment by Sapta-Dev27** [comment]
Yeah I made the CSS attractive 
U can check it in the below recording
[Screen recording 2024-01-06 18.19.14.webm](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/149397021/0fda5d93-2c5d-4092-b854-9ae1dd892e58)
