### ISSUE TITLE
Make the website Responsive for all devices ( in mobile , tabs )

### ISSUE THREAD

**Issue by Sapta-Dev27** [Corrupteddisk/SpotifycloneWeb#43]
Will try to make the website completely responsive for mobile devices and tabs by the use of media quaries

**Comment by rko0211** [comment]
I am also interested to work in this issue kindly assign me this one

**Comment by Koustavjr** [comment]
@Sapta-Dev27 assigned.

**Comment by rko0211** [comment]
Hello this issue is not resolve till now kindly assign me this one i want to work in this.

**Comment by Sapta-Dev27** [comment]
I am starting to work on this issue . I was having my 1st semester PCA and CA exams , so I was busy for the past few days
