### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by rko0211** [Corrupteddisk/SpotifycloneWeb#54]
![Screen Shot 2024-01-07 at 11 16 09](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/97402824/c4d7d574-e641-4c2f-b750-2edcd951c322)

**Comment by rko0211** [comment]
Hey kindly assign me this task ...

**Comment by Sayan044** [comment]
assigned to @rko0211 .
