### ISSUE TITLE
adding hover effect on arijits photo

### ISSUE THREAD

**Issue by YooAshu** [Corrupteddisk/SpotifycloneWeb#62]
when hover on arijit's photo it will flip and will show text about arijit singh

**Comment by Koustavjr** [comment]
@YooAshu assigned.

**Comment by Sayan044** [comment]
@YooAshu the photo is same as previous.
Please look into it.
https://corrupteddisk.github.io/SpotifycloneWeb/

**Comment by YooAshu** [comment]
Ok
