### ISSUE TITLE
add login button in the header of the website

### ISSUE THREAD

**Issue by AnuragMalasi** [Corrupteddisk/SpotifycloneWeb#69]
i will be adding a login button in the header which will direct the user to our login page.
![Screenshot 2024-01-10 121726](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/125523667/61da8e47-b6c8-4dcf-94dc-cbe1613e8bfd)

**Comment by AnuragMalasi** [comment]
@Koustavjr please assign this issue to me
thanks :)

**Comment by Sayan044** [comment]
Assigned to @AnuragMalasi .
you have 2 days to complete
