### ISSUE TITLE
Fix responsiveness of home page

### ISSUE THREAD

**Issue by lord-cyclone100** [Corrupteddisk/SpotifycloneWeb#72]
For small screens the home page looks distorted. I want to fix this @Sayan044 
![WhatsApp Image 2024-01-11 at 06 28 49_3747516d](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/121711381/bfc161e7-8d58-4a49-8d53-cc6f8800a564)

**Comment by Sayan044** [comment]
Assigned to @lord-cyclone100 
you have 3 days to complete.
