### ISSUE TITLE
[ENHANCEMENT] enhance the user interface of the website

### ISSUE THREAD

**Issue by AnuragMalasi** [Corrupteddisk/SpotifycloneWeb#76]
--> enhancing the whole sidebar of the website
--> adding links to the buttons created
--> adding language button on the sidebar
![Screenshot 2024-01-12 000753](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/125523667/b3c7702a-e8ee-4e98-b1ab-12e604c0c351)

**Comment by AnuragMalasi** [comment]
@Sayan044 please assign this issue to me
thanks :)

**Comment by Sayan044** [comment]
Assigned to @AnuragMalasi

**Comment by AnuragMalasi** [comment]
@Sayan044 i don't think it's assigned
please assign it again
thanks :)
