### ISSUE TITLE
Adding more genre of Arijit singh

### ISSUE THREAD

**Issue by YooAshu** [Corrupteddisk/SpotifycloneWeb#79]
Want to add more singers

**Comment by Sayan044** [comment]
Assigned to @YooAshu

**Comment by Sayan044** [comment]
@YooAshu Don't add other singers, but you can add different genres related to Arijit Singh.

**Comment by YooAshu** [comment]
Okay , this will be great

**Comment by YooAshu** [comment]
I submitted my previous PR , pls assign me for this issue

**Comment by YooAshu** [comment]
@Sayan044 pls assign me for this

**Comment by Sayan044** [comment]
yeah @YooAshu assigned
