### ISSUE TITLE
The website is not responsive for mobile view

### ISSUE THREAD

**Issue by rko0211** [Corrupteddisk/SpotifycloneWeb#81]
![Screen Shot 2024-01-12 at 02 59 05](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/97402824/14c4f375-0885-4949-8070-76e0665b34c1)

Although previously this issue already arised and some of them send their PR also but still the website is not responsive,
Please check this issue, and i want to work in it kindly assign me this task.

**Comment by soumit-s** [comment]
Assign @rko0211
