### ISSUE TITLE
About page issue

### ISSUE THREAD

**Issue by lord-cyclone100** [Corrupteddisk/SpotifycloneWeb#83]
The about page does not go hand in hand with the theme of Say music-Arijit Singh. Moreover it is not responsive.
If you like I would like to work on this issue. @Sayan044 
![Screenshot (339)](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/121711381/2e1a3d17-7eb9-43a1-8d7c-225198588a98)
![Screenshot (340)](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/121711381/f928558a-c7d2-4644-8aee-a47e7ea00932)

**Comment by Sayan044** [comment]
Assigned to @lord-cyclone100
