### ISSUE TITLE
Making a sign-up page

### ISSUE THREAD

**Issue by AnuragMalasi** [Corrupteddisk/SpotifycloneWeb#91]

**Comment by AnuragMalasi** [comment]
@Sayan044 please assign this issue to me
thanks :)

**Comment by Sayan044** [comment]
it's already done, please check once

**Comment by AnuragMalasi** [comment]
> it's already done, please check once

i can see only login page in the project. Sign-up page is not there

**Comment by AnuragMalasi** [comment]
@Sayan044 please assign this issue to me
Thanks :)

**Comment by Sayan044** [comment]
Assigned to @AnuragMalasi
