### ISSUE TITLE
Add new Feature : API boxes

### ISSUE THREAD

**Issue by apu52** [Corrupteddisk/SpotifycloneWeb#96]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/Corrupteddisk/SpotifycloneWeb/assets/114172928/9ea74da4-5515-407c-991a-de3a7b61e22c)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by Sayan044** [comment]
Assigned to @apu52 
you have 3 days to complete.
